baseURL = "https://felipeweb.dev/"
languageCode = "en-us"
disqusShortname = "felipewebcloud"
googleAnalytics = "UA-57220118-3"
title = "Felipeweb"
theme = "moti"

[permalinks]
fixed = ":title/"
blog  = ":slug"

[params]
author = "Felipeweb"
keywords = ["Golang (Gopher)", "Software Architecture", "Cloud Computing", "Agile", "Lean", "Java"]
avatar = "img/avatar.jpg"
resume = "resume.pdf"
dateform = "Jan 2, 2006"
lang = "en"
footertext = "written by felipeweb"
about = """
I am Felipe Oliveira and I am currently a Head of Product Engineering at Getup Cloud.
"""

[params.social]
linkedin      = "felipewebcloud"
twitter       = "_felipeweb"
github        = "felipeweb"

[[params.info]]
label = "Email"
value = "fpo@felipeweb.dev"
link = "mailto:fpo@felipeweb.dev"

[[params.info]]
label = "Address"
value = "Brazil, São Paulo, SP"
