# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "moti"
license = "MIT"
licenselink = "https://github.com/felipeweb/moti/blob/master/LICENSE"
description = "Portfolio and Resume HTML to Developers, Programmers and Freelancers, theme for Hugo."
homepage = "https://github.com/felipeweb/moti"
tags = ["clean", "minimal"]
features = ["responsive", "single page", "resume", "vcard", "portfolio"]
min_version = 0.15

[author]
  name = "Felipeweb"
  homepage = "https://felipeweb.dev"

# If porting an existing theme
[original]
  name = "Sarah"
  homepage = "https://github.com/avelino/hugo-theme-sarah"
  repo = "https://github.com/avelino/hugo-theme-sarah"
